# .github/classroom/classroom.yml

autograding:
  tests:
    - name: CalculateSum_WithEmptyArray_ReturnsZero
      setup: |
        dotnet restore
        dotnet build
      run: |
        dotnet test --filter "FullyQualifiedName~ParallelSumTests.ParallelSumCalculatorTests.CalculateSum_WithEmptyArray_ReturnsZero"
      points: 1

    - name: CalculateSum_WithSingleElement_ReturnsElementValue
      setup: |
        dotnet restore
        dotnet build
      run: |
        dotnet test --filter "FullyQualifiedName~ParallelSumTests.ParallelSumCalculatorTests.CalculateSum_WithSingleElement_ReturnsElementValue"
      points: 1

    - name: CalculateSum_WithMultipleElements_ReturnsCorrectSum
      setup: |
        dotnet restore
        dotnet build
      run: |
        dotnet test --filter "FullyQualifiedName~ParallelSumTests.ParallelSumCalculatorTests.CalculateSum_WithMultipleElements_ReturnsCorrectSum"
      points: 1

    - name: CalculateSum_WithLargeArray_ReturnsCorrectSum
      setup: |
        dotnet restore
        dotnet build
      run: |
        dotnet test --filter "FullyQualifiedName~ParallelSumTests.ParallelSumCalculatorTests.CalculateSum_WithLargeArray_ReturnsCorrectSum"
      points: 1
